import Navbar from "~/components/navbar/Navbar";
import "./globals.css";
import {Nunito} from "next/font/google";
import LoginModal from "~/components/modal/LoginModal";
import RegisterModal from "~/components/modal/RegisterModal";
import ToasterProvider from "~/providers/ToastProvider";
import {Footer} from "~/components/Footer";
import React from "react";
import {AuthProvider} from "~/providers/AuthProvider";
import Head from "next/head";

const font = Nunito({subsets: ["vietnamese"]});

export const metadata = {
    title: "Tech store",
    description: "Generated by create next app",
};

export default function RootLayout({children}: {
    children: React.ReactNode;
}) {

    return (
        <html lang="en">
        <Head>
            <link rel="shortcut icon" href="/favicon.png" type="image/x-icon"/>
        </Head>
        <body className={font.className}>
        <AuthProvider>
            <ToasterProvider/>
            <Navbar/>
            <LoginModal/>
            <RegisterModal/>
            {children}
            <Footer/>
        </AuthProvider>
        </body>
        </html>
    );
}
